package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ErrorRecordV2 error record v2
// swagger:model ErrorRecordV2
type ErrorRecordV2 struct {

	// Input document unique identifier the error refers to.
	ID string `json:"id,omitempty"`

	// Error message.
	Message string `json:"message,omitempty"`
}

// Validate validates this error record v2
func (m *ErrorRecordV2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
