package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// TopicAssignmentRecordV2 topic assignment record v2
// swagger:model TopicAssignmentRecordV2
type TopicAssignmentRecordV2 struct {

	// Document-to-topic affiliation score between 0 and 1. The lower a distance score the stronger the topic affiliation is.
	Distance float64 `json:"distance,omitempty"`

	// Identifier for the document. Equates to the ID included in the input.
	DocumentID string `json:"documentId,omitempty"`

	// The topic ID which the document has been assigned to.
	TopicID string `json:"topicId,omitempty"`
}

// Validate validates this topic assignment record v2
func (m *TopicAssignmentRecordV2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
