package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// InternalError internal error
// swagger:model InternalError
type InternalError struct {

	// code
	Code string `json:"code,omitempty"`

	// inner error
	InnerError *InternalError `json:"innerError,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this internal error
func (m *InternalError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateInnerError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var internalErrorTypeCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["invalidParameterValue","invalidRequestBodyFormat","missingRequiredHeader","invalidRequestContent","missingRequiredParameter"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		internalErrorTypeCodePropEnum = append(internalErrorTypeCodePropEnum, v)
	}
}

const (
	// InternalErrorCodeInvalidParameterValue captures enum value "invalidParameterValue"
	InternalErrorCodeInvalidParameterValue string = "invalidParameterValue"
	// InternalErrorCodeInvalidRequestBodyFormat captures enum value "invalidRequestBodyFormat"
	InternalErrorCodeInvalidRequestBodyFormat string = "invalidRequestBodyFormat"
	// InternalErrorCodeMissingRequiredHeader captures enum value "missingRequiredHeader"
	InternalErrorCodeMissingRequiredHeader string = "missingRequiredHeader"
	// InternalErrorCodeInvalidRequestContent captures enum value "invalidRequestContent"
	InternalErrorCodeInvalidRequestContent string = "invalidRequestContent"
	// InternalErrorCodeMissingRequiredParameter captures enum value "missingRequiredParameter"
	InternalErrorCodeMissingRequiredParameter string = "missingRequiredParameter"
)

// prop value enum
func (m *InternalError) validateCodeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, internalErrorTypeCodePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *InternalError) validateCode(formats strfmt.Registry) error {

	if swag.IsZero(m.Code) { // not required
		return nil
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *InternalError) validateInnerError(formats strfmt.Registry) error {

	if swag.IsZero(m.InnerError) { // not required
		return nil
	}

	if m.InnerError != nil {

		if err := m.InnerError.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
