package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// MultiLanguageInputV2 multi language input v2
// swagger:model MultiLanguageInputV2
type MultiLanguageInputV2 struct {

	// Unique, non-empty document identifier.
	ID string `json:"id,omitempty"`

	// This is the 2 letter ISO 639-1 representation of a language.
	//             For example, use "en" for English; "es" for Spanish etc.,
	Language string `json:"language,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this multi language input v2
func (m *MultiLanguageInputV2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
