package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DetectedLanguageV2 detected language v2
// swagger:model DetectedLanguageV2
type DetectedLanguageV2 struct {

	// A two letter representation of the detected language according to the ISO 639-1 standard (e.g. en, fr).
	Iso6391Name string `json:"iso6391Name,omitempty"`

	// Long name of a detected language (e.g. English, French).
	Name string `json:"name,omitempty"`

	// A confidence score between 0 and 1. Scores close to 1 indicate 100% certainty that the identified language is true.
	Score float64 `json:"score,omitempty"`
}

// Validate validates this detected language v2
func (m *DetectedLanguageV2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
