package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// ErrorResponse error response
// swagger:model ErrorResponse
type ErrorResponse struct {

	// code
	Code string `json:"code,omitempty"`

	// inner error
	InnerError *InternalError `json:"innerError,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this error response
func (m *ErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInnerError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorResponse) validateInnerError(formats strfmt.Registry) error {

	if swag.IsZero(m.InnerError) { // not required
		return nil
	}

	if m.InnerError != nil {

		if err := m.InnerError.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
